language: node_js
cache: yarn
dist: trusty
os: 
  - linux

node_js:
  - 12

script:
  - yarn build

after_success:
  - |
      if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_PULL_REQUEST" = "false" && "$TRAVIS_BRANCH" == "master" ]]; then
        git clone http://github.com/davisp/ghp-import &&
        echo "fourier.cgm616.me" > dist/CNAME
        ./ghp-import/ghp_import.py -n -p -f -m "Site upload" -r https://"$GH_TOKEN"@github.com/"$TRAVIS_REPO_SLUG.git" dist &&
        echo "Uploaded site to ghpages"
      fi